## This is the parameters related to query provided by human
## Related pkg: eris
##
## Author: Ferdian Pratama

int8 icase # Interaction case
int8 question
string[] lexicalinfo
---
string[] multi_responses